export const THAI_PROVINCES = [
  { id: '2', en: 'Amnat Charoen', th: 'อำนาจเจริญ', label: 'Amnat Charoen (อำนาจเจริญ)' },
  { id: '3', en: 'Ang Thong', th: 'อ่างทอง', label: 'Ang Thong (อ่างทอง)' },
  { id: '1', en: 'Bangkok', th: 'กรุงเทพมหานคร', label: 'Bangkok (กรุงเทพมหานคร)' },
  { id: '4', en: 'Bueng Kan', th: 'บึงกาฬ', label: 'Bueng Kan (บึงกาฬ)' },
  { id: '5', en: 'Buri Ram', th: 'บุรีรัมย์', label: 'Buri Ram (บุรีรัมย์)' },
  { id: '6', en: 'Chachoengsao', th: 'ฉะเชิงเทรา', label: 'Chachoengsao (ฉะเชิงเทรา)' },
  { id: '7', en: 'Chai Nat', th: 'ชัยนาท', label: 'Chai Nat (ชัยนาท)' },
  { id: '8', en: 'Chaiyaphum', th: 'ชัยภูมิ', label: 'Chaiyaphum (ชัยภูมิ)' },
  { id: '9', en: 'Chanthaburi', th: 'จันทบุรี', label: 'Chanthaburi (จันทบุรี)' },
  { id: '10', en: 'Chiang Mai', th: 'เชียงใหม่', label: 'Chiang Mai (เชียงใหม่)' },
  { id: '11', en: 'Chiang Rai', th: 'เชียงราย', label: 'Chiang Rai (เชียงราย)' },
  { id: '12', en: 'Chon Buri', th: 'ชลบุรี', label: 'Chon Buri (ชลบุรี)' },
  { id: '13', en: 'Chumphon', th: 'ชุมพร', label: 'Chumphon (ชุมพร)' },
  { id: '14', en: 'Kalasin', th: 'กาฬสินธุ์', label: 'Kalasin (กาฬสินธุ์)' },
  { id: '15', en: 'Kamphaeng Phet', th: 'กำแพงเพชร', label: 'Kamphaeng Phet (กำแพงเพชร)' },
  { id: '16', en: 'Kanchanaburi', th: 'กาญจนบุรี', label: 'Kanchanaburi (กาญจนบุรี)' },
  { id: '17', en: 'Khon Kaen', th: 'ขอนแก่น', label: 'Khon Kaen (ขอนแก่น)' },
  { id: '18', en: 'Krabi', th: 'กระบี่', label: 'Krabi (กระบี่)' },
  { id: '19', en: 'Lampang', th: 'ลำปาง', label: 'Lampang (ลำปาง)' },
  { id: '20', en: 'Lamphun', th: 'ลำพูน', label: 'Lamphun (ลำพูน)' },
  { id: '21', en: 'Loei', th: 'เลย', label: 'Loei (เลย)' },
  { id: '22', en: 'Lop Buri', th: 'ลพบุรี', label: 'Lop Buri (ลพบุรี)' },
  { id: '23', en: 'Mae Hong Son', th: 'แม่ฮ่องสอน', label: 'Mae Hong Son (แม่ฮ่องสอน)' },
  { id: '24', en: 'Maha Sarakham', th: 'มหาสารคาม', label: 'Maha Sarakham (มหาสารคาม)' },
  { id: '25', en: 'Mukdahan', th: 'มุกดาหาร', label: 'Mukdahan (มุกดาหาร)' },
  { id: '26', en: 'Nakhon Nayok', th: 'นครนายก', label: 'Nakhon Nayok (นครนายก)' },
  { id: '27', en: 'Nakhon Pathom', th: 'นครปฐม', label: 'Nakhon Pathom (นครปฐม)' },
  { id: '28', en: 'Nakhon Phanom', th: 'นครพนม', label: 'Nakhon Phanom (นครพนม)' },
  { id: '29', en: 'Nakhon Ratchasima', th: 'นครราชสีมา', label: 'Nakhon Ratchasima (นครราชสีมา)' },
  { id: '30', en: 'Nakhon Sawan', th: 'นครสวรรค์', label: 'Nakhon Sawan (นครสวรรค์)' },
  { id: '31', en: 'Nakhon Si Thammarat', th: 'นครศรีธรรมราช', label: 'Nakhon Si Thammarat (นครศรีธรรมราช)' },
  { id: '32', en: 'Nan', th: 'น่าน', label: 'Nan (น่าน)' },
  { id: '33', en: 'Narathiwat', th: 'นราธิวาส', label: 'Narathiwat (นราธิวาส)' },
  { id: '34', en: 'Nong Bua Lam Phu', th: 'หนองบัวลำภู', label: 'Nong Bua Lam Phu (หนองบัวลำภู)' },
  { id: '35', en: 'Nong Khai', th: 'หนองคาย', label: 'Nong Khai (หนองคาย)' },
  { id: '36', en: 'Nonthaburi', th: 'นนทบุรี', label: 'Nonthaburi (นนทบุรี)' },
  { id: '37', en: 'Pathum Thani', th: 'ปทุมธานี', label: 'Pathum Thani (ปทุมธานี)' },
  { id: '38', en: 'Pattani', th: 'ปัตตานี', label: 'Pattani (ปัตตานี)' },
  { id: '39', en: 'Phang Nga', th: 'พังงา', label: 'Phang Nga (พังงา)' },
  { id: '40', en: 'Phatthalung', th: 'พัทลุง', label: 'Phatthalung (พัทลุง)' },
  { id: '41', en: 'Phayao', th: 'พะเยา', label: 'Phayao (พะเยา)' },
  { id: '42', en: 'Phetchabun', th: 'เพชรบูรณ์', label: 'Phetchabun (เพชรบูรณ์)' },
  { id: '43', en: 'Phetchaburi', th: 'เพชรบุรี', label: 'Phetchaburi (เพชรบุรี)' },
  { id: '44', en: 'Phichit', th: 'พิจิตร', label: 'Phichit (พิจิตร)' },
  { id: '45', en: 'Phitsanulok', th: 'พิษณุโลก', label: 'Phitsanulok (พิษณุโลก)' },
  { id: '46', en: 'Phra Nakhon Si Ayutthaya', th: 'พระนครศรีอยุธยา', label: 'Phra Nakhon Si Ayutthaya (พระนครศรีอยุธยา)' },
  { id: '47', en: 'Phrae', th: 'แพร่', label: 'Phrae (แพร่)' },
  { id: '48', en: 'Phuket', th: 'ภูเก็ต', label: 'Phuket (ภูเก็ต)' },
  { id: '49', en: 'Prachin Buri', th: 'ปราจีนบุรี', label: 'Prachin Buri (ปราจีนบุรี)' },
  { id: '50', en: 'Prachuap Khiri Khan', th: 'ประจวบคีรีขันธ์', label: 'Prachuap Khiri Khan (ประจวบคีรีขันธ์)' },
  { id: '51', en: 'Ranong', th: 'ระนอง', label: 'Ranong (ระนอง)' },
  { id: '52', en: 'Ratchaburi', th: 'ราชบุรี', label: 'Ratchaburi (ราชบุรี)' },
  { id: '53', en: 'Rayong', th: 'ระยอง', label: 'Rayong (ระยอง)' },
  { id: '54', en: 'Roi Et', th: 'ร้อยเอ็ด', label: 'Roi Et (ร้อยเอ็ด)' },
  { id: '55', en: 'Sa Kaeo', th: 'สระแก้ว', label: 'Sa Kaeo (สระแก้ว)' },
  { id: '56', en: 'Sakon Nakhon', th: 'สกลนคร', label: 'Sakon Nakhon (สกลนคร)' },
  { id: '57', en: 'Samut Prakan', th: 'สมุทรปราการ', label: 'Samut Prakan (สมุทรปราการ)' },
  { id: '58', en: 'Samut Sakhon', th: 'สมุทรสาคร', label: 'Samut Sakhon (สมุทรสาคร)' },
  { id: '59', en: 'Samut Songkhram', th: 'สมุทรสงคราม', label: 'Samut Songkhram (สมุทรสงคราม)' },
  { id: '60', en: 'Saraburi', th: 'สระบุรี', label: 'Saraburi (สระบุรี)' },
  { id: '61', en: 'Satun', th: 'สตูล', label: 'Satun (สตูล)' },
  { id: '62', en: 'Sing Buri', th: 'สิงห์บุรี', label: 'Sing Buri (สิงห์บุรี)' },
  { id: '63', en: 'Si Sa Ket', th: 'ศรีสะเกษ', label: 'Si Sa Ket (ศรีสะเกษ)' },
  { id: '64', en: 'Songkhla', th: 'สงขลา', label: 'Songkhla (สงขลา)' },
  { id: '65', en: 'Sukhothai', th: 'สุโขทัย', label: 'Sukhothai (สุโขทัย)' },
  { id: '66', en: 'Suphan Buri', th: 'สุพรรณบุรี', label: 'Suphan Buri (สุพรรณบุรี)' },
  { id: '67', en: 'Surat Thani', th: 'สุราษฎร์ธานี', label: 'Surat Thani (สุราษฎร์ธานี)' },
  { id: '68', en: 'Surin', th: 'สุรินทร์', label: 'Surin (สุรินทร์)' },
  { id: '69', en: 'Tak', th: 'ตาก', label: 'Tak (ตาก)' },
  { id: '70', en: 'Trang', th: 'ตรัง', label: 'Trang (ตรัง)' },
  { id: '71', en: 'Trat', th: 'ตราด', label: 'Trat (ตราด)' },
  { id: '72', en: 'Ubon Ratchathani', th: 'อุบลราชธานี', label: 'Ubon Ratchathani (อุบลราชธานี)' },
  { id: '73', en: 'Udon Thani', th: 'อุดรธานี', label: 'Udon Thani (อุดรธานี)' },
  { id: '74', en: 'Uthai Thani', th: 'อุทัยธานี', label: 'Uthai Thani (อุทัยธานี)' },
  { id: '75', en: 'Uttaradit', th: 'อุตรดิตถ์', label: 'Uttaradit (อุตรดิตถ์)' },
  { id: '76', en: 'Yala', th: 'ยะลา', label: 'Yala (ยะลา)' },
  { id: '77', en: 'Yasothon', th: 'ยโสธร', label: 'Yasothon (ยโสธร)' }
];
