// Mapping of English / Alternative Province names to Official English Province Names
const PROVINCE_MAP = {
  'bangkok': 'Bangkok',
  'bkk': 'Bangkok',
  'krung thep': 'Bangkok',
  'krung thep maha nakhon': 'Bangkok',
  'krungthep': 'Bangkok',
  'samut prakan': 'Samut Prakan',
  'samutprakarn': 'Samut Prakan',
  'samutprakan': 'Samut Prakan',
  'nonthaburi': 'Nonthaburi',
  'pathum thani': 'Pathum Thani',
  'pathumthani': 'Pathum Thani',
  'phra nakhon si ayutthaya': 'Ayutthaya',
  'ayutthaya': 'Ayutthaya',
  'ayuthaya': 'Ayutthaya',
  'ang thong': 'Ang Thong',
  'angthong': 'Ang Thong',
  'lopburi': 'Lopburi',
  'lop buri': 'Lopburi',
  'sing buri': 'Sing Buri',
  'singburi': 'Sing Buri',
  'chai nat': 'Chai Nat',
  'chainat': 'Chai Nat',
  'saraburi': 'Saraburi',
  'nakhon nayok': 'Nakhon Nayok',
  'nakhonnayok': 'Nakhon Nayok',
  'nakhon pathom': 'Nakhon Pathom',
  'nakhonpathom': 'Nakhon Pathom',
  'samut sakhon': 'Samut Sakhon',
  'samutsakhon': 'Samut Sakhon',
  'samut songkhram': 'Samut Songkhram',
  'samutsongkhram': 'Samut Songkhram',
  'suphan buri': 'Suphan Buri',
  'suphanburi': 'Suphan Buri',
  'chon buri': 'Chon Buri',
  'chonburi': 'Chon Buri',
  'rayong': 'Rayong',
  'chanthaburi': 'Chanthaburi',
  'chantaburi': 'Chanthaburi',
  'trat': 'Trat',
  'chachoengsao': 'Chachoengsao',
  'prachin buri': 'Prachin Buri',
  'prachinburi': 'Prachin Buri',
  'sa kaeo': 'Sa Kaeo',
  'sakaeo': 'Sa Kaeo',
  'chiang mai': 'Chiang Mai',
  'chiangmai': 'Chiang Mai',
  'lamphun': 'Lamphun',
  'lampang': 'Lampang',
  'uttaradit': 'Uttaradit',
  'phrae': 'Phrae',
  'nan': 'Nan',
  'phayao': 'Phayao',
  'chiang rai': 'Chiang Rai',
  'chiangrai': 'Chiang Rai',
  'mae hong son': 'Mae Hong Son',
  'maehongson': 'Mae Hong Son',
  'nakhon sawan': 'Nakhon Sawan',
  'nakhonsawan': 'Nakhon Sawan',
  'uthai thani': 'Uthai Thani',
  'uthaithani': 'Uthai Thani',
  'kamphaeng phet': 'Kamphaeng Phet',
  'kamphaengphet': 'Kamphaeng Phet',
  'tak': 'Tak',
  'sukhothai': 'Sukhothai',
  'phitsanulok': 'Phitsanulok',
  'phichit': 'Phichit',
  'phetchabun': 'Phetchabun',
  'petchabun': 'Phetchabun',
  'nakhon ratchasima': 'Nakhon Ratchasima',
  'nakhonratchasima': 'Nakhon Ratchasima',
  'korat': 'Nakhon Ratchasima',
  'buri ram': 'Buri Ram',
  'buriram': 'Buri Ram',
  'surin': 'Surin',
  'si sa ket': 'Si Sa Ket',
  'sisaket': 'Si Sa Ket',
  'ubon ratchathani': 'Ubon Ratchathani',
  'ubonratchathani': 'Ubon Ratchathani',
  'ubon': 'Ubon Ratchathani',
  'yasothon': 'Yasothon',
  'chaiyaphum': 'Chaiyaphum',
  'amnat charoen': 'Amnat Charoen',
  'amnatcharoen': 'Amnat Charoen',
  'nong bua lam phu': 'Nong Bua Lam Phu',
  'nongbualamphu': 'Nong Bua Lam Phu',
  'khon kaen': 'Khon Kaen',
  'khonkaen': 'Khon Kaen',
  'udon thani': 'Udon Thani',
  'udonthani': 'Udon Thani',
  'udon': 'Udon Thani',
  'loei': 'Loei',
  'nong khai': 'Nong Khai',
  'nongkhai': 'Nong Khai',
  'maha sarakham': 'Maha Sarakham',
  'mahasarakham': 'Maha Sarakham',
  'roi et': 'Roi Et',
  'roiet': 'Roi Et',
  'kalasin': 'Kalasin',
  'sakon nakhon': 'Sakon Nakhon',
  'sakonnakhon': 'Sakon Nakhon',
  'nakhon phanom': 'Nakhon Phanom',
  'nakhonphanom': 'Nakhon Phanom',
  'mukdahan': 'Mukdahan',
  'bueng kan': 'Bueng Kan',
  'buengkan': 'Bueng Kan',
  'ratchaburi': 'Ratchaburi',
  'ratburi': 'Ratchaburi',
  'kanchanaburi': 'Kanchanaburi',
  'phetchaburi': 'Phetchaburi',
  'petchaburi': 'Phetchaburi',
  'prachuap khiri khan': 'Prachuap Khiri Khan',
  'prachuap': 'Prachuap Khiri Khan',
  'chumphon': 'Chumphon',
  'ranong': 'Ranong',
  'surat thani': 'Surat Thani',
  'suratthani': 'Surat Thani',
  'surat': 'Surat Thani',
  'phang nga': 'Phang Nga',
  'phangnga': 'Phang Nga',
  'phuket': 'Phuket',
  'krabi': 'Krabi',
  'nakhon si thammarat': 'Nakhon Si Thammarat',
  'nakhonsithammarat': 'Nakhon Si Thammarat',
  'trang': 'Trang',
  'phatthalung': 'Phatthalung',
  'satun': 'Satun',
  'songkhla': 'Songkhla',
  'pattani': 'Pattani',
  'yala': 'Yala',
  'narathiwat': 'Narathiwat'
};

const ENGLISH_TO_THAI_MAP = {
  'bangkok': 'กรุงเทพมหานคร',
  'bkk': 'กรุงเทพมหานคร',
  'amnat charoen': 'อำนาจเจริญ',
  'ang thong': 'อ่างทอง',
  'bueng kan': 'บึงกาฬ',
  'buri ram': 'บุรีรัมย์',
  'buriram': 'บุรีรัมย์',
  'chachoengsao': 'ฉะเชิงเทรา',
  'chai nat': 'ชัยนาท',
  'chainat': 'ชัยนาท',
  'chaiyaphum': 'ชัยภูมิ',
  'chanthaburi': 'จันทบุรี',
  'chiang mai': 'เชียงใหม่',
  'chiangmai': 'เชียงใหม่',
  'chiang rai': 'เชียงราย',
  'chiangrai': 'เชียงราย',
  'chon buri': 'ชลบุรี',
  'chonburi': 'ชลบุรี',
  'chumphon': 'ชุมพร',
  'kalasin': 'กาฬสินธุ์',
  'kamphaeng phet': 'กำแพงเพชร',
  'kanchanaburi': 'กาญจนบุรี',
  'khon kaen': 'ขอนแก่น',
  'khonkaen': 'ขอนแก่น',
  'krabi': 'กระบี่',
  'lampang': 'ลำปาง',
  'lamphun': 'ลำพูน',
  'loei': 'เลย',
  'lop buri': 'ลพบุรี',
  'lopburi': 'ลพบุรี',
  'mae hong son': 'แม่ฮ่องสอน',
  'maha sarakham': 'มหาสารคาม',
  'mukdahan': 'มุกดาหาร',
  'nakhon nayok': 'นครนายก',
  'nakhon pathom': 'นครปฐม',
  'nakhon phanom': 'นครพนม',
  'nakhon ratchasima': 'นครราชสีมา',
  'korat': 'นครราชสีมา',
  'nakhon sawan': 'นครสวรรค์',
  'nakhon si thammarat': 'นครศรีธรรมราช',
  'nan': 'น่าน',
  'narathiwat': 'นราธิวาส',
  'nong bua lam phu': 'หนองบัวลำภู',
  'nong khai': 'หนองคาย',
  'nonthaburi': 'นนทบุรี',
  'pathum thani': 'ปทุมธานี',
  'pathumthani': 'ปทุมธานี',
  'pattani': 'ปัตตานี',
  'phang nga': 'พังงา',
  'phatthalung': 'พัทลุง',
  'phayao': 'พะเยา',
  'phetchabun': 'เพชรบูรณ์',
  'phetchaburi': 'เพชรบุรี',
  'phichit': 'พิจิตร',
  'phitsanulok': 'พิษณุโลก',
  'phra nakhon si ayutthaya': 'พระนครศรีอยุธยา',
  'ayutthaya': 'พระนครศรีอยุธยา',
  'phrae': 'แพร่',
  'phuket': 'ภูเก็ต',
  'prachin buri': 'ปราจีนบุรี',
  'prachuap khiri khan': 'ประจวบคีรีขันธ์',
  'ranong': 'ระนอง',
  'ratchaburi': 'ราชบุรี',
  'rayong': 'ระยอง',
  'roi et': 'ร้อยเอ็ด',
  'sa kaeo': 'สระแก้ว',
  'sakon nakhon': 'สกลนคร',
  'samut prakan': 'สมุทรปราการ',
  'samutprakarn': 'สมุทรปราการ',
  'samut sakhon': 'สมุทรสาคร',
  'samut songkhram': 'สมุทรสงคราม',
  'saraburi': 'สระบุรี',
  'satun': 'สตูล',
  'sing buri': 'สิงห์บุรี',
  'si sa ket': 'ศรีสะเกษ',
  'songkhla': 'สงขลา',
  'sukhothai': 'สุโขทัย',
  'suphan buri': 'สุพรรณบุรี',
  'surat thani': 'สุราษฎร์ธานี',
  'surin': 'สุรินทร์',
  'tak': 'ตาก',
  'trang': 'ตรัง',
  'trat': 'ตราด',
  'ubon ratchathani': 'อุบลราชธานี',
  'ubon': 'อุบลราชธานี',
  'udon thani': 'อุดรธานี',
  'udon': 'อุดรธานี',
  'uthai thani': 'อุทัยธานี',
  'uttaradit': 'อุตรดิตถ์',
  'yala': 'ยะลา',
  'yasothon': 'ยโสธร'
};

/**
 * Normalizes and converts an English or alternative province name to clean Title Case.
 */
export function toThaiProvince(input) {
  if (!input || typeof input !== 'string') return 'Bangkok';
  const trimmed = input.trim().toLowerCase();
  if (PROVINCE_MAP[trimmed]) {
    return PROVINCE_MAP[trimmed];
  }
  return input.trim().split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join(' ');
}

/**
 * Formats a full license plate string to strictly use Thai province names without English parentheses or English names.
 * Example: "2ขก 3363 Bangkok (กรุงเทพมหานคร)" -> "2ขก 3363 กรุงเทพมหานคร"
 * Example: "2ขก 3363 Bangkok" -> "2ขก 3363 กรุงเทพมหานคร"
 */
export function formatDisplayPlate(plateStr) {
  if (!plateStr || typeof plateStr !== 'string') return '';
  let str = plateStr.trim();

  // If format contains "(English)" after Thai e.g. "กรุงเทพมหานคร (Bangkok)", strip English in parens
  str = str.replace(/\s*\([a-zA-Z\s,.-]+\)/g, '');

  // If format contains parentheses like "Bangkok (กรุงเทพมหานคร)", extract Thai inside parentheses
  if (str.includes('(') && str.includes(')')) {
    const thaiMatch = str.match(/\(([\u0E00-\u0E7F\s]+)\)/);
    if (thaiMatch && thaiMatch[1]) {
      const thaiProv = thaiMatch[1].trim();
      str = str.replace(/\s+[a-zA-Z\s,.-]+\s*\([\u0E00-\u0E7F\s]+\)/g, ` ${thaiProv}`);
      return str.trim();
    }
  }

  // Otherwise, replace English province words with Thai province equivalents
  for (const [enKey, thVal] of Object.entries(ENGLISH_TO_THAI_MAP)) {
    const regex = new RegExp(`\\b${enKey}\\b`, 'gi');
    if (regex.test(str)) {
      str = str.replace(regex, thVal);
    }
  }

  return str.trim();
}
