export const THAI_PROVINCES = [
  { id: '2', en: 'Amnat Charoen', th: 'อำนาจเจริญ', label: 'อำนาจเจริญ (Amnat Charoen)' },
  { id: '3', en: 'Ang Thong', th: 'อ่างทอง', label: 'อ่างทอง (Ang Thong)' },
  { id: '1', en: 'Bangkok', th: 'กรุงเทพมหานคร', label: 'กรุงเทพมหานคร (Bangkok)' },
  { id: '4', en: 'Bueng Kan', th: 'บึงกาฬ', label: 'บึงกาฬ (Bueng Kan)' },
  { id: '5', en: 'Buri Ram', th: 'บุรีรัมย์', label: 'บุรีรัมย์ (Buri Ram)' },
  { id: '6', en: 'Chachoengsao', th: 'ฉะเชิงเทรา', label: 'ฉะเชิงเทรา (Chachoengsao)' },
  { id: '7', en: 'Chai Nat', th: 'ชัยนาท', label: 'ชัยนาท (Chai Nat)' },
  { id: '8', en: 'Chaiyaphum', th: 'ชัยภูมิ', label: 'ชัยภูมิ (Chaiyaphum)' },
  { id: '9', en: 'Chanthaburi', th: 'จันทบุรี', label: 'จันทบุรี (Chanthaburi)' },
  { id: '10', en: 'Chiang Mai', th: 'เชียงใหม่', label: 'เชียงใหม่ (Chiang Mai)' },
  { id: '11', en: 'Chiang Rai', th: 'เชียงราย', label: 'เชียงราย (Chiang Rai)' },
  { id: '12', en: 'Chon Buri', th: 'ชลบุรี', label: 'ชลบุรี (Chon Buri)' },
  { id: '13', en: 'Chumphon', th: 'ชุมพร', label: 'ชุมพร (Chumphon)' },
  { id: '14', en: 'Kalasin', th: 'กาฬสินธุ์', label: 'กาฬสินธุ์ (Kalasin)' },
  { id: '15', en: 'Kamphaeng Phet', th: 'กำแพงเพชร', label: 'กำแพงเพชร (Kamphaeng Phet)' },
  { id: '16', en: 'Kanchanaburi', th: 'กาญจนบุรี', label: 'กาญจนบุรี (Kanchanaburi)' },
  { id: '17', en: 'Khon Kaen', th: 'ขอนแก่น', label: 'ขอนแก่น (Khon Kaen)' },
  { id: '18', en: 'Krabi', th: 'กระบี่', label: 'กระบี่ (Krabi)' },
  { id: '19', en: 'Lampang', th: 'ลำปาง', label: 'ลำปาง (Lampang)' },
  { id: '20', en: 'Lamphun', th: 'ลำพูน', label: 'ลำพูน (Lamphun)' },
  { id: '21', en: 'Loei', th: 'เลย', label: 'เลย (Loei)' },
  { id: '22', en: 'Lop Buri', th: 'ลพบุรี', label: 'ลพบุรี (Lop Buri)' },
  { id: '23', en: 'Mae Hong Son', th: 'แม่ฮ่องสอน', label: 'แม่ฮ่องสอน (Mae Hong Son)' },
  { id: '24', en: 'Maha Sarakham', th: 'มหาสารคาม', label: 'มหาสารคาม (Maha Sarakham)' },
  { id: '25', en: 'Mukdahan', th: 'มุกดาหาร', label: 'มุกดาหาร (Mukdahan)' },
  { id: '26', en: 'Nakhon Nayok', th: 'นครนายก', label: 'นครนายก (Nakhon Nayok)' },
  { id: '27', en: 'Nakhon Pathom', th: 'นครปฐม', label: 'นครปฐม (Nakhon Pathom)' },
  { id: '28', en: 'Nakhon Phanom', th: 'นครพนม', label: 'นครพนม (Nakhon Phanom)' },
  { id: '29', en: 'Nakhon Ratchasima', th: 'นครราชสีมา', label: 'นครราชสีมา (Nakhon Ratchasima)' },
  { id: '30', en: 'Nakhon Sawan', th: 'นครสวรรค์', label: 'นครสวรรค์ (Nakhon Sawan)' },
  { id: '31', en: 'Nakhon Si Thammarat', th: 'นครศรีธรรมราช', label: 'นครศรีธรรมราช (Nakhon Si Thammarat)' },
  { id: '32', en: 'Nan', th: 'น่าน', label: 'น่าน (Nan)' },
  { id: '33', en: 'Narathiwat', th: 'นราธิวาส', label: 'นราธิวาส (Narathiwat)' },
  { id: '34', en: 'Nong Bua Lam Phu', th: 'หนองบัวลำภู', label: 'หนองบัวลำภู (Nong Bua Lam Phu)' },
  { id: '35', en: 'Nong Khai', th: 'หนองคาย', label: 'หนองคาย (Nong Khai)' },
  { id: '36', en: 'Nonthaburi', th: 'นนทบุรี', label: 'นนทบุรี (Nonthaburi)' },
  { id: '37', en: 'Pathum Thani', th: 'ปทุมธานี', label: 'ปทุมธานี (Pathum Thani)' },
  { id: '38', en: 'Pattani', th: 'ปัตตานี', label: 'ปัตตานี (Pattani)' },
  { id: '39', en: 'Phang Nga', th: 'พังงา', label: 'พังงา (Phang Nga)' },
  { id: '40', en: 'Phatthalung', th: 'พัทลุง', label: 'พัทลุง (Phatthalung)' },
  { id: '41', en: 'Phayao', th: 'พะเยา', label: 'พะเยา (Phayao)' },
  { id: '42', en: 'Phetchabun', th: 'เพชรบูรณ์', label: 'เพชรบูรณ์ (Phetchabun)' },
  { id: '43', en: 'Phetchaburi', th: 'เพชรบุรี', label: 'เพชรบุรี (Phetchaburi)' },
  { id: '44', en: 'Phichit', th: 'พิจิตร', label: 'พิจิตร (Phichit)' },
  { id: '45', en: 'Phitsanulok', th: 'พิษณุโลก', label: 'พิษณุโลก (Phitsanulok)' },
  { id: '46', en: 'Phra Nakhon Si Ayutthaya', th: 'พระนครศรีอยุธยา', label: 'พระนครศรีอยุธยา (Phra Nakhon Si Ayutthaya)' },
  { id: '47', en: 'Phrae', th: 'แพร่', label: 'แพร่ (Phrae)' },
  { id: '48', en: 'Phuket', th: 'ภูเก็ต', label: 'ภูเก็ต (Phuket)' },
  { id: '49', en: 'Prachin Buri', th: 'ปราจีนบุรี', label: 'ปราจีนบุรี (Prachin Buri)' },
  { id: '50', en: 'Prachuap Khiri Khan', th: 'ประจวบคีรีขันธ์', label: 'ประจวบคีรีขันธ์ (Prachuap Khiri Khan)' },
  { id: '51', en: 'Ranong', th: 'ระนอง', label: 'ระนอง (Ranong)' },
  { id: '52', en: 'Ratchaburi', th: 'ราชบุรี', label: 'ราชบุรี (Ratchaburi)' },
  { id: '53', en: 'Rayong', th: 'ระยอง', label: 'ระยอง (Rayong)' },
  { id: '54', en: 'Roi Et', th: 'ร้อยเอ็ด', label: 'ร้อยเอ็ด (Roi Et)' },
  { id: '55', en: 'Sa Kaeo', th: 'สระแก้ว', label: 'สระแก้ว (Sa Kaeo)' },
  { id: '56', en: 'Sakon Nakhon', th: 'สกลนคร', label: 'สกลนคร (Sakon Nakhon)' },
  { id: '57', en: 'Samut Prakan', th: 'สมุทรปราการ', label: 'สมุทรปราการ (Samut Prakan)' },
  { id: '58', en: 'Samut Sakhon', th: 'สมุทรสาคร', label: 'สมุทรสาคร (Samut Sakhon)' },
  { id: '59', en: 'Samut Songkhram', th: 'สมุทรสงคราม', label: 'สมุทรสงคราม (Samut Songkhram)' },
  { id: '60', en: 'Saraburi', th: 'สระบุรี', label: 'สระบุรี (Saraburi)' },
  { id: '61', en: 'Satun', th: 'สตูล', label: 'สตูล (Satun)' },
  { id: '62', en: 'Sing Buri', th: 'สิงห์บุรี', label: 'สิงห์บุรี (Sing Buri)' },
  { id: '63', en: 'Si Sa Ket', th: 'ศรีสะเกษ', label: 'ศรีสะเกษ (Si Sa Ket)' },
  { id: '64', en: 'Songkhla', th: 'สงขลา', label: 'สงขลา (Songkhla)' },
  { id: '65', en: 'Sukhothai', th: 'สุโขทัย', label: 'สุโขทัย (Sukhothai)' },
  { id: '66', en: 'Suphan Buri', th: 'สุพรรณบุรี', label: 'สุพรรณบุรี (Suphan Buri)' },
  { id: '67', en: 'Surat Thani', th: 'สุราษฎร์ธานี', label: 'สุราษฎร์ธานี (Surat Thani)' },
  { id: '68', en: 'Surin', th: 'สุรินทร์', label: 'สุรินทร์ (Surin)' },
  { id: '69', en: 'Tak', th: 'ตาก', label: 'ตาก (Tak)' },
  { id: '70', en: 'Trang', th: 'ตรัง', label: 'ตรัง (Trang)' },
  { id: '71', en: 'Trat', th: 'ตราด', label: 'ตราด (Trat)' },
  { id: '72', en: 'Ubon Ratchathani', th: 'อุบลราชธานี', label: 'อุบลราชธานี (Ubon Ratchathani)' },
  { id: '73', en: 'Udon Thani', th: 'อุดรธานี', label: 'อุดรธานี (Udon Thani)' },
  { id: '74', en: 'Uthai Thani', th: 'อุทัยธานี', label: 'อุทัยธานี (Uthai Thani)' },
  { id: '75', en: 'Uttaradit', th: 'อุตรดิตถ์', label: 'อุตรดิตถ์ (Uttaradit)' },
  { id: '76', en: 'Yala', th: 'ยะลา', label: 'ยะลา (Yala)' },
  { id: '77', en: 'Yasothon', th: 'ยโสธร', label: 'ยโสธร (Yasothon)' }
];
