// Mapping of English / Alternative Province names to Official English Province Names
const PROVINCE_MAP = {
  'bangkok': 'Bangkok',
  'bkk': 'Bangkok',
  'krung thep': 'Bangkok',
  'krung thep maha nakhon': 'Bangkok',
  'krungthep': 'Bangkok',
  'samut prakan': 'Samut Prakan',
  'samutprakarn': 'Samut Prakan',
  'samutprakan': 'Samut Prakan',
  'nonthaburi': 'Nonthaburi',
  'pathum thani': 'Pathum Thani',
  'pathumthani': 'Pathum Thani',
  'phra nakhon si ayutthaya': 'Ayutthaya',
  'ayutthaya': 'Ayutthaya',
  'ayuthaya': 'Ayutthaya',
  'ang thong': 'Ang Thong',
  'angthong': 'Ang Thong',
  'lopburi': 'Lopburi',
  'lop buri': 'Lopburi',
  'sing buri': 'Sing Buri',
  'singburi': 'Sing Buri',
  'chai nat': 'Chai Nat',
  'chainat': 'Chai Nat',
  'saraburi': 'Saraburi',
  'nakhon nayok': 'Nakhon Nayok',
  'nakhonnayok': 'Nakhon Nayok',
  'nakhon pathom': 'Nakhon Pathom',
  'nakhonpathom': 'Nakhon Pathom',
  'samut sakhon': 'Samut Sakhon',
  'samutsakhon': 'Samut Sakhon',
  'samut songkhram': 'Samut Songkhram',
  'samutsongkhram': 'Samut Songkhram',
  'suphan buri': 'Suphan Buri',
  'suphanburi': 'Suphan Buri',
  'chon buri': 'Chon Buri',
  'chonburi': 'Chon Buri',
  'rayong': 'Rayong',
  'chanthaburi': 'Chanthaburi',
  'chantaburi': 'Chanthaburi',
  'trat': 'Trat',
  'chachoengsao': 'Chachoengsao',
  'prachin buri': 'Prachin Buri',
  'prachinburi': 'Prachin Buri',
  'sa kaeo': 'Sa Kaeo',
  'sakaeo': 'Sa Kaeo',
  'chiang mai': 'Chiang Mai',
  'chiangmai': 'Chiang Mai',
  'lamphun': 'Lamphun',
  'lampang': 'Lampang',
  'uttaradit': 'Uttaradit',
  'phrae': 'Phrae',
  'nan': 'Nan',
  'phayao': 'Phayao',
  'chiang rai': 'Chiang Rai',
  'chiangrai': 'Chiang Rai',
  'mae hong son': 'Mae Hong Son',
  'maehongson': 'Mae Hong Son',
  'nakhon sawan': 'Nakhon Sawan',
  'nakhonsawan': 'Nakhon Sawan',
  'uthai thani': 'Uthai Thani',
  'uthaithani': 'Uthai Thani',
  'kamphaeng phet': 'Kamphaeng Phet',
  'kamphaengphet': 'Kamphaeng Phet',
  'tak': 'Tak',
  'sukhothai': 'Sukhothai',
  'phitsanulok': 'Phitsanulok',
  'phichit': 'Phichit',
  'phetchabun': 'Phetchabun',
  'petchabun': 'Phetchabun',
  'nakhon ratchasima': 'Nakhon Ratchasima',
  'nakhonratchasima': 'Nakhon Ratchasima',
  'korat': 'Nakhon Ratchasima',
  'buri ram': 'Buri Ram',
  'buriram': 'Buri Ram',
  'surin': 'Surin',
  'si sa ket': 'Si Sa Ket',
  'sisaket': 'Si Sa Ket',
  'ubon ratchathani': 'Ubon Ratchathani',
  'ubonratchathani': 'Ubon Ratchathani',
  'ubon': 'Ubon Ratchathani',
  'yasothon': 'Yasothon',
  'chaiyaphum': 'Chaiyaphum',
  'amnat charoen': 'Amnat Charoen',
  'amnatcharoen': 'Amnat Charoen',
  'nong bua lam phu': 'Nong Bua Lam Phu',
  'nongbualamphu': 'Nong Bua Lam Phu',
  'khon kaen': 'Khon Kaen',
  'khonkaen': 'Khon Kaen',
  'udon thani': 'Udon Thani',
  'udonthani': 'Udon Thani',
  'udon': 'Udon Thani',
  'loei': 'Loei',
  'nong khai': 'Nong Khai',
  'nongkhai': 'Nong Khai',
  'maha sarakham': 'Maha Sarakham',
  'mahasarakham': 'Maha Sarakham',
  'roi et': 'Roi Et',
  'roiet': 'Roi Et',
  'kalasin': 'Kalasin',
  'sakon nakhon': 'Sakon Nakhon',
  'sakonnakhon': 'Sakon Nakhon',
  'nakhon phanom': 'Nakhon Phanom',
  'nakhonphanom': 'Nakhon Phanom',
  'mukdahan': 'Mukdahan',
  'bueng kan': 'Bueng Kan',
  'buengkan': 'Bueng Kan',
  'ratchaburi': 'Ratchaburi',
  'ratburi': 'Ratchaburi',
  'kanchanaburi': 'Kanchanaburi',
  'phetchaburi': 'Phetchaburi',
  'petchaburi': 'Phetchaburi',
  'prachuap khiri khan': 'Prachuap Khiri Khan',
  'prachuap': 'Prachuap Khiri Khan',
  'chumphon': 'Chumphon',
  'ranong': 'Ranong',
  'surat thani': 'Surat Thani',
  'suratthani': 'Surat Thani',
  'surat': 'Surat Thani',
  'phang nga': 'Phang Nga',
  'phangnga': 'Phang Nga',
  'phuket': 'Phuket',
  'krabi': 'Krabi',
  'nakhon si thammarat': 'Nakhon Si Thammarat',
  'nakhonsithammarat': 'Nakhon Si Thammarat',
  'trang': 'Trang',
  'phatthalung': 'Phatthalung',
  'satun': 'Satun',
  'songkhla': 'Songkhla',
  'pattani': 'Pattani',
  'yala': 'Yala',
  'narathiwat': 'Narathiwat'
};

/**
 * Normalizes and converts an English or alternative province name to clean Title Case.
 */
export function toThaiProvince(input) {
  if (!input || typeof input !== 'string') return 'Bangkok';
  const trimmed = input.trim().toLowerCase();
  if (PROVINCE_MAP[trimmed]) {
    return PROVINCE_MAP[trimmed];
  }
  return input.trim().split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join(' ');
}
